config/routes.rb
Rails.application.routes.draw do
  resources :notifications, only: :index

  devise_for :users do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  root to: 'static_pages#home'
  get 'search', to: 'accommodations#search'
  resources :dashboards, only: [:index]

  resources :accommodations do
    resources :bookings
  end

  get :favorites, to: 'favorites#index'
  post   "favorites/:accommodation_id/create"  => "favorites#create"
  delete "favorites/:accommodation_id/destroy" => "favorites#destroy"

  resources :comments, only: [:create, :destroy]

  resources :bookings
end

app/models/accommodation.rb
class Accommodation < ApplicationRecord
  TYPES = ["Family", "Business", "Single", "other"]
  belongs_to :user
  has_one_attached :photo
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy
  default_scope -> { order(created_at: :desc) }
  validates :name, presence: true, uniqueness: true, length: { minimum: 3 }
  validates :price, presence: true
  validates :description, presence: true, length: { minimum: 3 }

  def accommodation_comment(accommodation_id)
    Comment.where("accommodation_id = ?", accommodation_id)
  end
end

app/controllers/accommodations_controller.rb
class AccommodationsController < ApplicationController
  before_action :search
  def index
    @accommodations = Accommodation.all

    if user_signed_in?
      @q = Accommodation.ransack(params[:q])
      @accommodations = @q.result(distinct: true)
    end
  end

  def search
    @search_word = params[:q][:location_cont] if params[:q]
    @q = Accommodation.search(search_params)
    @accommodation = @q.result(distinct: true)
  end

  def show
    @accommodation = Accommodation.find(params[:id])
    @user = @accommodation.user
    @comment = Comment.new
    @comments = @accommodation.accommodation_comment(@accommodation.id)
  end

  def new
    @accommodation = Accommodation.new
    @user = @accommodation.user
  end

  def create
    @accommodation = Accommodation.new(accommodation_params)
    @user = current_user
    @accommodation.user = @user
    @accommodation.available = true
    if @accommodation.save
      redirect_to accommodations_path
    else
      render :new
    end
  end

  def edit
    @accommodation = Accommodation.find(params[:id])
  end

  def update
    @accommodation = Accommodation.find(params[:id])
    @accommodation.update(accommodation_params)
    redirect_to accommodation_path
  end

  def destroy
    @accommodation = Accommodation.find(params[:id])
    @accommodation.destroy
    respond_to do |format|
      format.html { redirect_to dashboards_path, notice: 'Accommodation was successfully deleted!' }
    end
  end

  private

  def accommodation_params
    params.require(:accommodation).permit(:name, :description, :price, :location, :available, :property_type, :photo)
  end

  def search_params
  end
end

app/views/accommodations/edit.html.erb
<div class="container">
  <h1>Edit <%= @accommodation.name %></h1>
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= simple_form_for [@user, @accommodation] do |f|%>
        <%= f.input :name %>
        <%= f.input :description %>
        <%= f.input :price %>
        <%= f.input :location %>
        <%= f.input :property_type, collection: Accommodation::TYPES %>
        <%= f.input :photo, as: :file %>
        <%= f.button :submit, value: 'Edit Accommodation', class: 'btn btn-primary' %>
        <%= link_to 'Cancel', dashboards_path %> |
        <%= link_to 'Home', accommodations_path %>
      <% end %>
    </div>
  </div>
</div>

app/views/accommodations/index.html.erb
<div class="container">
    <% if @search_word.present? %>
      <h3>Searched by location "<%= @search_word %>"： <%= @accommodations.count %> results</h3>
    <% else %>
      <h3>Accommodations</h3>
      <%= link_to 'Add accommodation', new_accommodation_path, class: 'btn btn-primary' %>
    <% end %>
    <div class="cards">
    <% @accommodations.each do |accommodation| %>
        <%= link_to accommodation_path(accommodation) do %>
          <% if accommodation.photo.attached? %>
            <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path accommodation.photo.key %>')">
          <% else %>
            <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path "https://res.cloudinary.com/dq6gibxhn/image/upload/v1603843635/8wha00enorrdh9suh8p7ztvt18td.jpg" %>')">
          <% end %>
            <ul>
              <li><%= accommodation.location %></li>
              <li>Type: <%= accommodation.property_type %> </li>
              <li>Price: $<%= accommodation.price %>/day</li>
              <% if current_user == accommodation.user %>
                <li id="mine">It's your accommodation</li>
                <!-- below 'elsif' related to app/controllers/accommodations_controller.rb line 56-58 -->
              <% elsif accommodation.available == true %> 
                <li id="book">You can book!</li>
              <% else %>
                <li id="notavailable">Sorry not available...</li>
              <% end %>
            </ul>
          </div>
        <% end %>
      <% end %>
    </div>
</div>

app/views/accommodations/new.html.erb
<div class="container">
  <h1>Add new accommodation</h1>
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= simple_form_for [@user, @accommodation] do |f|%>
        <%= f.input :name %>
        <%= f.input :description %>
        <%= f.input :price %>
        <%= f.input :location %>
        <%= f.input :property_type, collection: Accommodation::TYPES %>
        <%= f.input :photo, as: :file %>
        <%= f.button :submit, value: 'Add Accommodation', class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>
</div>

app/views/accommodations/show.html.erb
<div class="container">
  <h3><%= @accommodation.name %> @ <%= @accommodation.location %></h3>
    <div class="card-trip">
    　<% if @accommodation.photo.attached? %>
      　<%= cl_image_tag @accommodation.photo.key, height: 150, width: 200, crop: :fill %>
      <% else %>
        <img src="https://res.cloudinary.com/dq6gibxhn/image/upload/v1603843635/8wha00enorrdh9suh8p7ztvt18td.jpg" %>
      <% end  %>
      <div class="card-trip-infos">
        <div>
          <p class="card-text">Description: <%= @accommodation.description %></p>
          <p class="card-text">Type: <%= @accommodation.property_type %></p>
          <p id="price">$<%= @accommodation.price %>/day</p>
          <% if current_user != @accommodation.user %>
            <%= render 'users/favorite_form' %>
          <% end %>  
        </div>
        <% if current_user == @accommodation.user %>
          <div>
            <%= link_to 'edit', edit_accommodation_path(@accommodation), class: 'btn btn-success' %> 
            <%= link_to "delete", accommodation_path(@accommodation), method: :delete, data: { confirm: "Are you sure?" }, class: 'btn btn-warning' %>
          </div>
        <% elsif @accommodation.available == true  %>
          <%= link_to 'Book', new_accommodation_booking_path(@accommodation), class: 'btn btn-primary' %>
        <% else %>
          <p>Sorry not available... <%= link_to 'See other accommodations', accommodations_path %></p>
        <% end %>  
    </div>
    <div class="comment">
    　<%= render "comments/accommodation_comments" %>
      <%= render "comments/new" %>
    </div>
  </div>
</div>