config/routes.rb
Rails.application.routes.draw do
  resources :notifications, only: :index

  devise_for :users do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  root to: 'static_pages#home'
  get 'search', to: 'accommodations#search'
  resources :dashboards, only: [:index]

  resources :accommodations do
    resources :bookings
  end

  get :favorites, to: 'favorites#index'
  post   "favorites/:accommodation_id/create"  => "favorites#create"
  delete "favorites/:accommodation_id/destroy" => "favorites#destroy"

  resources :comments, only: [:create, :destroy]

  resources :bookings
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :user
  validates :user_id, presence: true
  validates :accommodation_id, presence: true
  validates :variety, presence: true
  validates :from_user_id, presence: true
  default_scope -> { order(created_at: :desc) }
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  def index
    @notifications = current_user.notifications
    # blow code seems not work. 
    # What I want to do is: after user see notification index page, notification attribute is changed to false.
    # As notifications should be disapper once user see it.
    current_user.update_attribute(:notification, false)
  end
end

app/views/notifications/_notification.html.erb
<% user = User.find(notification.from_user_id) %>
<% accommodation = Accommodation.find(notification.accommodation_id) %>
<li id="notification-<%= notification.id %>">
  <div>
    <% if notification.variety == 1 %>
      <p><%= notification.created_at.strftime("%Y/%m/%d(%a) %H:%M") %></p>
      <p class="notification-message">Your <%= link_to accommodation.name, accommodation_path(accommodation) %> was added to favorite by <%= user.user_name %></p>
    <% elsif notification.variety == 2 %>
      <p><%= notification.created_at.strftime("%Y/%m/%d(%a) %H:%M") %></p>
      <p class="notification-message">Your <%= link_to accommodation.name, accommodation_path(accommodation) %> got comment by <%= user.user_name %>
      「<%= notification.content %>」</p>
    <% end %>
  </div>
</li>

app/views/notifications/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h3>　Notifications</h3>
    </div>
  </div>
  <% if @notifications.present? %>
    <ol class="notifications">
      <%= render @notifications %>
    </ol>
  <% end %>
</div>