config/routes.rb
Rails.application.routes.draw do
  resources :notifications, only: :index

  devise_for :users do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  root to: 'static_pages#home'
  get 'search', to: 'accommodations#search'
  resources :dashboards, only: [:index]

  resources :accommodations do
    resources :bookings
  end

  get :favorites, to: 'favorites#index'
  post   "favorites/:accommodation_id/create"  => "favorites#create"
  delete "favorites/:accommodation_id/destroy" => "favorites#destroy"

  resources :comments, only: [:create, :destroy]

  resources :bookings
end

app/models/booking.rb
class Booking < ApplicationRecord
  STATUS = ["Available", "Booked"]
  belongs_to :user
  belongs_to :accommodation
  validates :status, inclusion: { in: Booking::STATUS }
  validate  :date_not_before_today
  validate  :end_date_not_before_start_date

  def date_not_before_today
    errors.add(:start_date, "should be after today") if start_date < Date.today
  end

  def end_date_not_before_start_date
    errors.add(:end_date, "should be after start date") if end_date < start_date
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:show, :edit, :update, :destroy]

  def index
    @bookings = Booking.where(user: current_user)
  end

  def show
  end

  def new
    @booking = Booking.new
    @accommodation = Accommodation.find(params[:accommodation_id])
  end

  def create
    @booking = Booking.new(booking_params)
    @accommodation = Accommodation.find(params[:accommodation_id])
    @booking.accommodation = @accommodation
    @booking.user = current_user
    @booking.total_price = calculated_price
    @booking.status = "Booked"

    if @booking.save
      @accommodation = Accommodation.find(params[:accommodation_id])
      @accommodation.available = false
      @accommodation.save
      redirect_to booking_path(@booking), notice: 'Booking was successfully created.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    @accommodation = Accommodation.find(params[:accommodation_id])
    if @booking.update(booking_params)
      @booking.total_price = calculated_price
      @booking.save
      redirect_to @booking, notice: 'Booking was successfully updated.'
    else
      render :edit
    end
  end

  def calculated_price
   (@accommodation.price * (@booking.end_date - @booking.start_date).to_i)
  end

  def destroy
    # Below line 56-58 are seems not work.
    # What I want to do is: after booking destroy, accommodation.available is chanded to true.
    # As other user can book.
    # @accommodation = Accommodation.find(params[:accommodation_id])
    # @accommodation.available = true
    # @accommodation.save
    @booking.destroy
    redirect_to bookings_path, notice: 'Booking was successfully canceled.'
  end

  private

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def booking_params
    params.require(:booking).permit(:total_price, :start_date, :end_date, :status)
  end
end

app/views/bookings/_form.html.erb
<%= simple_form_for [@accommodation, @booking] do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :start_date %>
  </div>

  <div class="form-inputs">
    <%= f.input :end_date %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/bookings/edit.html.erb
<div class="container bookings">
  <h1>Edit Booking</h1>
  <%= simple_form_for [@booking.accommodation, @booking] do |f| %>
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

    <div class="form-inputs">
      <%= f.input :start_date %>
    </div>

    <div class="form-inputs">
      <%= f.input :end_date %>
    </div>

    <div class="form-actions">
      <%= f.button :submit %>
    </div>
  <% end %>
  <%= link_to 'See detail', accommodation_booking_path(@booking.accommodation, @booking) %> |
  <%= link_to 'Back to booking list', bookings_path %>
</div>

app/views/bookings/index.html.erb
<div class="container">
  <h3>My Bookings(<%= @bookings.count %>)</h3>
    <% @bookings.each do |booking| %>
      <%= link_to booking_path(booking) do %>
        <div class="card-product">
          <% if booking.accommodation.photo.attached? %>
            <%= cl_image_tag booking.accommodation.photo.key, width: 300 %>
          <% else %>
            <%= cl_image_tag src="https://res.cloudinary.com/dq6gibxhn/image/upload/v1603843635/8wha00enorrdh9suh8p7ztvt18td.jpg", width: 300 %>
          <% end  %>
          <div class=card-product-infos>
            <p class="card-title"><%= booking.accommodation.name %> @ <%= booking.accommodation.location %></p>
            <p class="card-text">Description: <%= booking.accommodation.description %></p>
            <p class="card-text">Type: <%= booking.accommodation.property_type %></p>
            <p class="card-text">From: <%= booking.start_date %></p>
            <p class="card-text">To: <%= booking.start_date %></p>
            <p id="price">Total Price: $ <%= booking.total_price %> / <%= (booking.end_date - booking.start_date).to_i %>days</p>
          </div>
        </div>
      <% end %>
  　<% end %>
</div>

app/views/bookings/new.html.erb
<div class="container bookings">
  <h1>Book <%= @accommodation.name %></h1>
  <%= render 'form', booking: @booking %>
  <%= link_to 'Back', accommodations_path %>
</div>

app/views/bookings/show.html.erb
<div class="container">
  <h3>Your booking <%= @booking.accommodation.name %></h3>
  <div class="card-trip">
    <% if @booking.accommodation.photo.attached? %>
      <%= cl_image_tag @booking.accommodation.photo.key, height: 150, width: 200, crop: :fill %>
    <% else %>
      <%= cl_image_tag src="https://res.cloudinary.com/dq6gibxhn/image/upload/v1603843635/8wha00enorrdh9suh8p7ztvt18td.jpg", height: 150, width: 200, crop: :fill %>
    <% end  %>
    <div class="card-trip-infos">
      <div>
        <p class="card-title">Location: <%= @booking.accommodation.location %></p>
        <p class="card-text">Description: <%= @booking.accommodation.description %></p>
        <p class="card-text">Type: <%= @booking.accommodation.property_type %></p>
        <p class="card-text">Start Date: <%= @booking.start_date %></p>
        <p class="card-text">End Date: <%= @booking.end_date %></p>
        <p class="card-text">Status: <%= @booking.status %></p>
        <p id="price">Total Price: $ <%= @booking.total_price %> / <%= (@booking.end_date - @booking.start_date).to_i %>days</p>
      </div>
      <% if current_user == @booking.user %>
        <div>
          <%= link_to 'Edit', edit_booking_path, class: 'btn btn-success' %> 
          <%= link_to "Cancel", booking_path(@booking), method: :delete, data: { confirm: "Are you sure?" }, class: 'btn btn-warning' %>
        </div>
        <% else %>
          <%= link_to 'Back to Dashboard', dashboards_path %>
        <% end %>  
    </div>
  </div>
</div>