config/routes.rb
Rails.application.routes.draw do
  resources :notifications, only: :index

  devise_for :users do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  root to: 'static_pages#home'
  get 'search', to: 'accommodations#search'
  resources :dashboards, only: [:index]

  resources :accommodations do
    resources :bookings
  end

  get :favorites, to: 'favorites#index'
  post   "favorites/:accommodation_id/create"  => "favorites#create"
  delete "favorites/:accommodation_id/destroy" => "favorites#destroy"

  resources :comments, only: [:create, :destroy]

  resources :bookings
end

app/views/layouts/_footer.html.erb
<footer>
  <div class="container">
    <div class="row copyright">
      <div class="col-md-12 text-center">
        <p>
          <%= cl_image_tag src="https://res.cloudinary.com/dq6gibxhn/image/upload/v1604716098/ba0fdwejowiolih916xo.png", height: 30, width: 70, crop: :fill %>
          <small class="block">&copy; 2020 AirbnbTest by Marisa Tsubokura.</small>
          <a href="https://github.com/Marisa090588T/airbnb"><i class="fab fa-github"></i></a>
        </p>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
 <div>
   <nav>
    <%= render 'layouts/search' if user_signed_in? %>
     <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
        <li><i class="fas fa-home"><%= link_to 'Accommodation', accommodations_path %></i></li>
          <% if current_user.notification == true %>
            <li class="new_notification header-link">
          <% else %>
            <li class="no_notification header-link">
          <% end %>
          <i class="fas fa-bell"><%= link_to 'Notification', notifications_path %></i></li>
        <li><i class="fas fa-heart"><%= link_to 'Favorite', favorites_path %></i></li>
        <li><i class="fas fa-list-alt"><%= link_to 'Booking', bookings_path %></i></li>
        <li><i class="fas fa-user-cog"><%= link_to "Manege", dashboards_path(@user) %></i></li>
        <li><i class="fas fa-sign-out-alt"><%= link_to "Log out", destroy_user_session_path, method: :get %></i></li> 
        <% else %>
          <li><i class="fas fa-user-plus"><%= link_to 'Sign up', new_user_registration_path %></i></li>
          <li><i class="fas fa-sign-in-alt"><%= link_to 'Log in', new_user_session_path %></i></li>
        <% end %>
     </ul>
   </nav>
  </div>
</header>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= csp_meta_tag %>

<%= stylesheet_link_tag    'application', media: 'all',
                           'data-turbolinks-track': 'reload' %>
<%# <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
<script src="https://kit.fontawesome.com/84eeecacff.js" crossorigin="anonymous"></script>

app/views/layouts/_search.html.erb
<div class="row">
  <%= search_form_for @q do |f| %>
    <div class="col-md-10">
      <div class='form-group'>
        <%= f.search_field :location_cont, placeholder: "Search accommodations by location", class: 'form-control font-awesome' %>
      </div>
    </div>
    <div class="col-md-2">
      <div class='form-group'>
        <%= f.submit nil, class: 'btn btn-primary' %>
      </div>
    </div>
  <% end %>
</div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE HTML>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= render 'layouts/rails_default' %>
    <%= render 'layouts/shim' %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
 　 <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  
  <body>
    <div id="page">
      <%= render 'layouts/header' %>
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>